name: Deploy BFF to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Testes (se houver)
        run: echo "Adicionar testes futuramente"

      - name: Deploy via Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Verificar se o serviço está rodando
        run: |
          for i in {1..10}; do
            if curl -sSf https://fiap-bff.onrender.com/health; then
              echo "Serviço está rodando!"
              exit 0
            fi
            echo "Aguardando serviço iniciar..."
            sleep 10
          done
          echo "Serviço não iniciou a tempo." && exit 1
